export KONG_API="http://0.0.0.0:8001/"
export SERVICE_URL="http://0.0.0.0:5000/"
export POSTGRES_USER="murabei"
export POSTGRES_DB="murabei"
export POSTGRES_PASSWORD="is_very_nice!"
export FLASK_APP="app.py"
